import * as XLSX from "xlsx";
import {
  formatAssetType,
  formatAssetRoadHeadline,
  formatLevel,
  formatStatus,
} from "@/lib/inspection";
import { severityLabel } from "@/lib/severities";
import { formatAppDate, formatAppPattern } from "@/lib/date-time";
import type {
  FormPayload,
  InspectionTemplate,
} from "@/lib/inspection-template-types";
import {
  fieldFilled,
  formatFormFieldDisplayValue,
} from "@/lib/inspection-template-types";
import type {
  ReportPdfAsset,
  ReportPdfCategory,
  ReportPdfDefect,
  ReportPdfInput,
} from "@/lib/report-pdf";

export type ReportExcelInput = Omit<
  ReportPdfInput,
  "includeFormPhotos"
> & {
  asset: ReportPdfAsset;
  categories: ReportPdfCategory[];
  defects: ReportPdfDefect[];
  template?: InspectionTemplate | null;
  formPayload?: FormPayload | null;
};

function sheet(rows: Record<string, string | number | null | undefined>[]) {
  return XLSX.utils.json_to_sheet(rows.length ? rows : [{ Note: "No rows" }]);
}

function safeSheetName(name: string, used: Set<string>): string {
  let base = name.replace(/[\\/?*[\]]/g, " ").replace(/\s+/g, " ").trim();
  if (!base) base = "Sheet";
  base = base.slice(0, 31);
  let candidate = base;
  let n = 2;
  while (used.has(candidate.toLowerCase())) {
    const suffix = ` (${n})`;
    candidate = `${base.slice(0, Math.max(1, 31 - suffix.length))}${suffix}`;
    n += 1;
  }
  used.add(candidate.toLowerCase());
  return candidate;
}

/**
 * Excel report shaped like the WRU / DoT Level 2 workbook the app was seeded from:
 * Cover · template pages (Structure info, Inventory, …) · Condition Rating ·
 * Structure Defect & Treatment · Categories.
 */
export function buildInspectionExcel(input: ReportExcelInput): Buffer {
  const road = formatAssetRoadHeadline(input.asset);
  const values = input.formPayload?.values ?? {};
  const usedNames = new Set<string>();
  const wb = XLSX.utils.book_new();

  const cover = [
    { Field: "Title", Value: input.titleLabel },
    { Field: "Asset number", Value: input.asset.assetNumber },
    { Field: "Asset name", Value: input.asset.name },
    { Field: "Asset type", Value: formatAssetType(input.asset.type) },
    { Field: "Road", Value: road },
    { Field: "Location", Value: input.asset.location ?? "" },
    { Field: "Classification", Value: input.asset.classification ?? "" },
    {
      Field: "Sub-classification",
      Value: input.asset.subClassification ?? "",
    },
    { Field: "Inspection type", Value: formatLevel(input.level) },
    { Field: "Status", Value: formatStatus(input.status) },
    {
      Field: "Inspected",
      Value: formatAppDate(input.inspectedAt, "datetime"),
    },
    {
      Field: "Submitted",
      Value: formatAppDate(input.submittedAt, "datetime"),
    },
    {
      Field: "Approved",
      Value: input.approvedAt
        ? formatAppDate(input.approvedAt, "datetime")
        : "",
    },
    { Field: "Inspector", Value: input.inspectorName },
    { Field: "Inspector detail", Value: input.inspectorDetail ?? "" },
    { Field: "Approver", Value: input.approverName ?? "" },
    { Field: "Approver detail", Value: input.approverDetail ?? "" },
    { Field: "Reviewer", Value: input.reviewerName ?? "" },
    { Field: "General comments", Value: input.generalComments ?? "" },
    {
      Field: "Export kind",
      Value: input.scopeOnly ? "Scope export" : "Full report",
    },
    { Field: "Generated by", Value: input.generatedByName ?? "" },
    {
      Field: "Template",
      Value: input.template?.label ?? formatLevel(input.level),
    },
  ];
  XLSX.utils.book_append_sheet(
    wb,
    sheet(cover),
    safeSheetName("Cover", usedNames),
  );

  // One sheet per inspection-template page (WRU L1/L2 structure).
  if (input.template && !input.scopeOnly) {
    for (const page of input.template.pages) {
      if (page.builtin) continue;
      const rows: Record<string, string>[] = [];
      for (const section of page.sections) {
        for (const field of section.fields) {
          const raw = values[field.id];
          if (!fieldFilled(raw) && field.type !== "component_table") continue;
          if (field.type === "component_table") {
            rows.push({
              Section: section.title,
              Field: field.label,
              Value: formatFormFieldDisplayValue(field, raw),
            });
            continue;
          }
          if (!fieldFilled(raw)) continue;
          rows.push({
            Section: section.title,
            Field: field.label,
            Value: formatFormFieldDisplayValue(field, raw),
          });
        }
      }
      if (!rows.length) continue;
      XLSX.utils.book_append_sheet(
        wb,
        sheet(rows),
        safeSheetName(page.title, usedNames),
      );
    }
  }

  // Dedicated Condition Rating sheet (DoT workbook name).
  if (input.template && !input.scopeOnly) {
    const crField = input.template.pages
      .flatMap((p) => p.sections.flatMap((s) => s.fields))
      .find((f) => f.type === "component_table" || f.id === "cr_components");
    if (crField && fieldFilled(values[crField.id])) {
      let parsed: unknown = values[crField.id];
      try {
        parsed =
          typeof parsed === "string" ? JSON.parse(parsed) : parsed;
      } catch {
        /* keep */
      }
      const rows: Record<string, string | number>[] = [];
      if (Array.isArray(parsed)) {
        for (const row of parsed) {
          if (!row || typeof row !== "object") continue;
          const r = row as Record<string, unknown>;
          rows.push({
            Component: String(r.name ?? r.label ?? r.id ?? ""),
            Qty: String(r.qty ?? r.quantity ?? ""),
            CS1: String(r.cs1 ?? r.CS1 ?? ""),
            CS2: String(r.cs2 ?? r.CS2 ?? ""),
            CS3: String(r.cs3 ?? r.CS3 ?? ""),
            CS4: String(r.cs4 ?? r.CS4 ?? ""),
            Notes: String(r.notes ?? r.comments ?? ""),
          });
        }
      }
      if (rows.length) {
        XLSX.utils.book_append_sheet(
          wb,
          sheet(rows),
          safeSheetName("Condition Rating", usedNames),
        );
      }
    }
  }

  const defectRows = input.defects.map((d, i) => ({
    "#": i + 1,
    "Defect code": d.defectCode,
    Description: d.description,
    "Condition state": severityLabel(d.severity),
    Category: d.category ?? "",
    Subcategory: d.subcategory ?? "",
    Comments: d.comments ?? "",
    "Photo path": d.photoPath ?? "",
  }));
  XLSX.utils.book_append_sheet(
    wb,
    sheet(defectRows),
    safeSheetName("Structure Defect & Treatment", usedNames),
  );

  if (input.categories.length && !input.scopeOnly) {
    const categoryRows = input.categories.map((c) => ({
      Category: c.category,
      Subcategory: c.subcategory,
      Comments: c.comments ?? "",
    }));
    XLSX.utils.book_append_sheet(
      wb,
      sheet(categoryRows),
      safeSheetName("Categories", usedNames),
    );
  }

  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

export function excelFilename(input: {
  assetNumber: string;
  inspectedAt: Date;
  level: string;
  scopeOnly?: boolean;
}) {
  const date = formatAppPattern(input.inspectedAt, "ddMMyyyy");
  const level = formatLevel(input.level).replace(/\s+/g, "");
  const kind = input.scopeOnly ? "Scope" : "InspectionDetailReport";
  return `${input.assetNumber}_${level}_${kind}_${date}.xlsx`;
}
