import * as XLSX from "xlsx";
import {
  formatAssetType,
  formatAssetRoadHeadline,
  formatLevel,
  formatStatus,
} from "@/lib/inspection";
import { severityLabel } from "@/lib/severities";
import { formatAppDate, formatAppPattern } from "@/lib/date-time";
import type {
  FormPayload,
  InspectionTemplate,
} from "@/lib/inspection-template-types";
import {
  fieldFilled,
  formatFormFieldDisplayValue,
} from "@/lib/inspection-template-types";
import type {
  ReportPdfAsset,
  ReportPdfCategory,
  ReportPdfDefect,
  ReportPdfInput,
} from "@/lib/report-pdf";

export type ReportExcelInput = Omit<
  ReportPdfInput,
  "includeFormPhotos"
> & {
  asset: ReportPdfAsset;
  categories: ReportPdfCategory[];
  defects: ReportPdfDefect[];
  template?: InspectionTemplate | null;
  formPayload?: FormPayload | null;
};

function sheet(rows: Record<string, string | number | null | undefined>[]) {
  return XLSX.utils.json_to_sheet(rows.length ? rows : [{ Note: "No rows" }]);
}

/** Spreadsheet mirror of the inspection report (summary, form, defects). */
export function buildInspectionExcel(input: ReportExcelInput): Buffer {
  const road = formatAssetRoadHeadline(input.asset);
  const values = input.formPayload?.values ?? {};

  const summary = [
    { Field: "Title", Value: input.titleLabel },
    { Field: "Asset number", Value: input.asset.assetNumber },
    { Field: "Asset name", Value: input.asset.name },
    { Field: "Asset type", Value: formatAssetType(input.asset.type) },
    { Field: "Road", Value: road },
    { Field: "Location", Value: input.asset.location ?? "" },
    {
      Field: "Classification",
      Value: input.asset.classification ?? "",
    },
    {
      Field: "Sub-classification",
      Value: input.asset.subClassification ?? "",
    },
    { Field: "Inspection type", Value: formatLevel(input.level) },
    { Field: "Status", Value: formatStatus(input.status) },
    {
      Field: "Inspected",
      Value: formatAppDate(input.inspectedAt, "datetime"),
    },
    {
      Field: "Submitted",
      Value: formatAppDate(input.submittedAt, "datetime"),
    },
    {
      Field: "Approved",
      Value: input.approvedAt
        ? formatAppDate(input.approvedAt, "datetime")
        : "",
    },
    { Field: "Inspector", Value: input.inspectorName },
    {
      Field: "Inspector detail",
      Value: input.inspectorDetail ?? "",
    },
    { Field: "Approver", Value: input.approverName ?? "" },
    {
      Field: "Approver detail",
      Value: input.approverDetail ?? "",
    },
    { Field: "Reviewer", Value: input.reviewerName ?? "" },
    {
      Field: "General comments",
      Value: input.generalComments ?? "",
    },
    {
      Field: "Export kind",
      Value: input.scopeOnly ? "Scope export" : "Full report",
    },
    {
      Field: "Generated by",
      Value: input.generatedByName ?? "",
    },
  ];

  const formRows: Record<string, string>[] = [];
  if (input.template && !input.scopeOnly) {
    for (const page of input.template.pages) {
      for (const section of page.sections) {
        for (const field of section.fields) {
          if (!fieldFilled(values[field.id])) continue;
          formRows.push({
            Page: page.title,
            Section: section.title,
            Field: field.label,
            Value: formatFormFieldDisplayValue(field, values[field.id]),
          });
        }
      }
    }
  }

  const categoryRows = input.categories.map((c) => ({
    Category: c.category,
    Subcategory: c.subcategory,
    Comments: c.comments ?? "",
  }));

  const defectRows = input.defects.map((d, i) => ({
    "#": i + 1,
    "Defect code": d.defectCode,
    Description: d.description,
    "Condition state": severityLabel(d.severity),
    Category: d.category ?? "",
    Subcategory: d.subcategory ?? "",
    Comments: d.comments ?? "",
  }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet(summary), "Summary");
  if (formRows.length) {
    XLSX.utils.book_append_sheet(wb, sheet(formRows), "Form");
  }
  if (categoryRows.length) {
    XLSX.utils.book_append_sheet(wb, sheet(categoryRows), "Categories");
  }
  XLSX.utils.book_append_sheet(wb, sheet(defectRows), "Defects");

  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

export function excelFilename(input: {
  assetNumber: string;
  inspectedAt: Date;
  level: string;
  scopeOnly?: boolean;
}) {
  const date = formatAppPattern(input.inspectedAt, "ddMMyyyy");
  const level = formatLevel(input.level).replace(/\s+/g, "");
  const kind = input.scopeOnly ? "Scope" : "InspectionDetailReport";
  return `${input.assetNumber}_${level}_${kind}_${date}.xlsx`;
}
